name: Unzip project.zip

on:
  push:
    paths:
      - 'project.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip file
        run: |
          mkdir unzipped
          unzip project.zip -d unzipped
